# Generated by Django 4.2 on 2024-11-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zaliczenie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
