# Generated by Django 4.2 on 2024-11-13 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_www', '0004_alter_osoba_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='osoby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
